// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: available_names.sql

package database

import (
	"context"
)

const insertName = `-- name: InsertName :one
INSERT INTO available_names (name, country_code)
VALUES (
    $1,
    $2
)

RETURNING id, name, country_code
`

type InsertNameParams struct {
	Name        string
	CountryCode string
}

func (q *Queries) InsertName(ctx context.Context, arg InsertNameParams) (AvailableName, error) {
	row := q.db.QueryRowContext(ctx, insertName, arg.Name, arg.CountryCode)
	var i AvailableName
	err := row.Scan(&i.ID, &i.Name, &i.CountryCode)
	return i, err
}
