// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: available_last_names.sql

package database

import (
	"context"
	"database/sql"
)

const insertLastName = `-- name: InsertLastName :one
INSERT INTO available_last (name, country_code)
VALUES (
    $1,
    $2
)

RETURNING id, name, country_code
`

type InsertLastNameParams struct {
	Name        string
	CountryCode sql.NullString
}

func (q *Queries) InsertLastName(ctx context.Context, arg InsertLastNameParams) (AvailableLast, error) {
	row := q.db.QueryRowContext(ctx, insertLastName, arg.Name, arg.CountryCode)
	var i AvailableLast
	err := row.Scan(&i.ID, &i.Name, &i.CountryCode)
	return i, err
}
