// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: countries.sql

package database

import (
	"context"
)

const insertCountry = `-- name: InsertCountry :one
INSERT INTO countries (country_code, country_name)
VALUES (
    $1,
    $2
)

RETURNING country_code, country_name
`

type InsertCountryParams struct {
	CountryCode string
	CountryName string
}

func (q *Queries) InsertCountry(ctx context.Context, arg InsertCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, insertCountry, arg.CountryCode, arg.CountryName)
	var i Country
	err := row.Scan(&i.CountryCode, &i.CountryName)
	return i, err
}
