// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type AvailableLast struct {
	ID          int32
	Name        string
	CountryCode string
}

type AvailableName struct {
	ID          int32
	Name        string
	CountryCode string
}

type AvailablePassword struct {
	ID       int32
	Password string
}

type Country struct {
	CountryCode string
	CountryName string
}

type User struct {
	ID          int32
	Username    string
	Password    string
	CountryCode string
}
