// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type AvailableLast struct {
	ID          int32
	Name        string
	CountryCode sql.NullString
}

type AvailableName struct {
	ID          int32
	Name        string
	CountryCode sql.NullString
}

type AvailablePassword struct {
	ID       int32
	Password string
}

type Country struct {
	CountryCode string
	CountryName string
}

type User struct {
	ID          int32
	Name        sql.NullString
	LastName    sql.NullString
	Password    sql.NullString
	CountryCode sql.NullString
}
