// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, country_Code)
VALUES (
    $1,
    $2,
    $3
)

RETURNING id, username, password, country_code
`

type CreateUserParams struct {
	Username    string
	Password    string
	CountryCode string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.CountryCode)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CountryCode,
	)
	return i, err
}
