// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, last_name, password, country_Code)
VALUES (
    $1,
    $2,
    $3,
    $4
)

RETURNING id, name, last_name, password, country_code
`

type CreateUserParams struct {
	Name        sql.NullString
	LastName    sql.NullString
	Password    sql.NullString
	CountryCode sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.LastName,
		arg.Password,
		arg.CountryCode,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Password,
		&i.CountryCode,
	)
	return i, err
}
