version: "3.9"  # Or your preferred version

services:
  postgres:
    image: postgres:15 # Or your desired PostgreSQL version
    container_name: postgres_db # Give your container a name
    ports:
      - "5432:5432" # Map port 5432 on your host to 5432 in the container
    environment:
      POSTGRES_USER: root # Replace with your desired username
      POSTGRES_PASSWORD: root # Replace with a strong password
      POSTGRES_DB: stultux # Replace with your desired database name
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data across container restarts
    restart: always # Ensure the container restarts if it crashes

volumes:
  postgres_data: # Define the volume
