package main

import (
	"flag"
	"fmt"

	"github.com/joho/godotenv"
	_ "github.com/lib/pq"

	_ "github.com/sebosun/stultux/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/sebosun/stultux/seeders"
)

// @title My API
// @version 1.0
// @description This is a sample API using Swaggo.
// @host localhost:1323
// @BasePath /api

func main() {
	godotenv.Load(".env")

	flag.Parse()
	args := flag.Args()

	if len(args) > 0 {
		if args[0] == "seed" {
            fmt.Println("init seed")
			seeders.InitSeed()
		}
	} 

    RunServer()
}
