// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/7/2025, 10:06:37 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/sebastian/Code/Projects/stultux/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/Code/Projects/stultux/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/Code/Projects/stultux/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/Code/Projects/stultux/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/Code/Projects/stultux/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/Code/Projects/stultux/plugins/**/*.{js,ts,mjs}","/home/sebastian/Code/Projects/stultux/composables/**/*.{js,ts,mjs}","/home/sebastian/Code/Projects/stultux/utils/**/*.{js,ts,mjs}","/home/sebastian/Code/Projects/stultux/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/Code/Projects/stultux/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/sebastian/Code/Projects/stultux/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})();

export default resolvedConfig;