info:
  contact: {}
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: This endpoint returns a simple hello message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Returns a simple greeting
      tags:
      - example
swagger: "2.0"
